#!/bin/sh

MAX=$(($(cat /sys/class/backlight/intel_backlight/max_brightness) - 1))
CURRENT=$(cat /sys/class/backlight/intel_backlight/brightness)

NEW=$(($CURRENT $1 $2))

NEW=$(($NEW > $MAX ? $MAX : $NEW))
NEW=$(($NEW < 0 ? 0 : $NEW))

echo $NEW > /sys/class/backlight/intel_backlight/brightness
