#!/bin/bash

# deal with tearing
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"

xrandr --output HDMI-0 --auto --scale 2x2 --mode 2560x1440 --rate 144.00 --output eDP-1-1 --auto --pos 5120x720
# xrandr --output HDMI-0 --auto --scale 2x2 --rate 144.00 --output eDP-1-1 --off
