#!/bin/bash

# deal with tearing
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"

# xrandr --output hdmi-0 --auto --scale 2x2 --output edp-1-1 --auto --pos 3840x0
xrandr --output HDMI-0 --auto --scale 2x2 --output eDP-1-1 --auto --pos 5120x500
# xrandr --output HDMI-0 --mode 2560x1440 --pos 0x0 --transform 2,0,0,0,2,0,0,0,1 --output eDP-1-1 --mode 3840x2160 --pos 5120x500 --primary

# xrandr --output HDMI-1-0 --mode 2560x1440 --scale 1x1 --output eDP-1 --auto --pos 5120x500

# attempt to work in hybrid
# xrandr --output HDMI-1-0 --mode 2560x1440 --pos 0x0 --transform 2,0,0,0,2,0,0,0,1 --output eDP-1 --mode 3840x2160 --pos 5120x500 --primary
