#!/usr/bin/env python
import sys
import http.server
from http.server import SimpleHTTPRequestHandler

class Handler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

if __name__ == '__main__':
    port = 3000
    try:
        port = int(sys.argv[1])
    except:
        pass
    http.server.test(Handler, port=port)
